---
- name: Database Layer
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - variable.yml

  pre_tasks:
    - name: Common Setup
      ansible.builtin.import_tasks:
        tasks/common_setup.yml

    - name: Cleanup MySQL
      when: run_cleanup_mysql_before_install
      ansible.builtin.include_tasks:
        tasks/cleanup_mysql.yml

    - name: Cleanup Redis
      when: run_cleanup_redis_before_install
      ansible.builtin.include_tasks:
        tasks/cleanup_redis.yml

    - name: Cleanup PostgreSQL
      when: run_cleanup_postgresql_before_install
      ansible.builtin.include_tasks:
        tasks/cleanup_postgresql.yml

  tasks:
    - name: Install MySQL
      ansible.builtin.import_tasks:
        tasks/install_mysql.yml

    - name: Install Redis
      ansible.builtin.import_tasks:
        tasks/install_redis.yml

    - name: Install PostgreSQL
      ansible.builtin.import_tasks:
        tasks/install_postgresql.yml
