---
- name: MySQL Backup and Encryption Setup
  hosts: servers
  become: true
  gather_facts: false
  tasks:
    - name: Ensure required package is installed
      ansible.builtin.apt:
        name:
          - python3
          - python3-venv
        state: present

    - name: Rsync all files to server
      ansible.posix.synchronize:
        src: ../tools/
        dest: /data/src/mysql-backup
        recursive: true
        rsync_opts:
          - "--exclude:_*"

    - name: Create python virtual environment
      ansible.builtin.command: python3 -m venv /data/src/mysql-backup/.venv
      args:
        creates: /data/src/mysql-backup/bin/activate

    - name: Install requirements.txt into the venv
      ansible.builtin.pip:
        requirements: /data/src/mysql-backup/requirements.txt
        virtualenv: /data/src/mysql-backup/.venv
        virtualenv_python: python3
