---
- name: Common Setup
  block:
    - name: Update system packages
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure required directories is created
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop: "{{ common_directories }}"

    - name: Ensure required packages is installed
      ansible.builtin.apt:
        name: "{{ common_packages }}"
        state: present
