services:
  app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    image: 10.255.2.4/devops-internship/spring-app:latest
    ports:
      - "8080:8080"

    volumes:
      - ./logs:/app/logs

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
