# --------------------------------------------------
# NAMESPACE
# --------------------------------------------------

apiVersion: v1
kind: Namespace
metadata:
  name: prd
  labels:
    name: prd

---
# --------------------------------------------------
# RESOURCE QUOTA: Limit resources for namespace
# --------------------------------------------------

apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    pods: "50"
    configmaps: "100"
    secrets: "100"

---
# --------------------------------------------------
# LIMIT RANGE: Limit resources for pod/container
# --------------------------------------------------

apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limitrange
  namespace: dev
spec:
  limits:
  - type: Container
    default:
      cpu: "1"
      memory: "1Gi"
    max:
      cpu: "4"
      memory: "4Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
  - type: Pod
    max:
      cpu: "8"
      memory: "8Gi"
